package com.nphkhiem.englishforyourchildren.data.profile

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One child, as a row.
 *
 * The key is the domain's own identifier rather than an autogenerated number, because storage does
 * not get to define who a child is, and a key that only exists after an insert is useless to the
 * caller building the profile it is about to save.
 *
 * [ageBand] holds the enum's name and not its ordinal. An ordinal means whatever the order of the
 * enum happens to be, so reordering `AgeBand` would silently age every child in the database. A
 * name that no longer matches breaks loudly, which is the failure worth having.
 *
 * [createdAt] exists only to order the picker. The domain model does not carry it, because when a
 * row was written is a fact about the row rather than about the child, but without it SQLite may
 * return profiles in any order and a child's face could move between launches.
 */
@Entity(tableName = "child_profile")
data class ChildProfileEntity(
    @PrimaryKey val id: String,
    val nickname: String,
    val ageBand: String,
    val avatarId: String,
    val createdAt: Long
)
